# Run clang-tidy
name: Clang-tidy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - requirements.txt
      - LICENSE.txt
      - .pre-commit-config.yaml
      - '**/*.md'
      - '**/*.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - requirements.txt
      - LICENSE.txt
      - .pre-commit-config.yaml
      - '**/*.md'
      - '**/*.yml'

jobs:
  checkout-and-check-formatting:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clang-tidy
      uses: HorstBaerbel/action-clang-tidy@1.2
      # These are optional (defaults displayed)
      with:
        scandir: '.'
        builddir: 'build'
        excludedirs: ''
        extensions: 'c,h,cc,hh'
        cmakeoptions: ''
